name: Scheduled Price Check

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-price-check-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Function
        run: |
          curl -X GET "https://YOUR-NETLIFY-SITE-NAME.netlify.app/.netlify/functions/scheduled-price-check?key=${{ secrets.SCHEDULER_SECRET_KEY }}"
      - name: Log completion
        run: echo "Price check completed at $(date)"